### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by ZdenoPavlik** [Danielku15/swagger-codegen-cpprestsdk#2]
Hello, 
I am trying to make running this project, but when I am running CompileAndGenerate.bat directly after pull, it fails with message "Could not find or load main class io.swagger.codegen.SwaggerCodegen".

What to do with this?

**Comment by Danielku15** [comment]
Hi. 
This project was already integrated into the official [swagger-codegen](https://github.com/swagger-api/swagger-codegen). There is not need to rely on this repository. 

The error is very likely caused by a failed compilation. The batch script does not check for any compilation errors. Maybe you are lacking of the required environment setup (maven, JDK etc.) which causes the packaging to fail.
